name: "Website update"

on:
  push:
    branches:
      - "**"
      - "!gh-pages"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 3 * * MON"
  workflow_dispatch:
    inputs:
      reset_github_pages:
        description: "Reset the gh-pages branch (yes or no; default: no). Remember to set the gh-pages branch back in Settings -> Pages!"

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
    - name: Clone website repository on current branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Determine which token to use when cloning website repository on gh-pages branch
      id: token_gh_pages
      run: |
        if [[ "${GITHUB_REPOSITORY}" == "FEMlium/femlium.github.io" ]]; then
          echo "token=${{ secrets.GITHUB_TOKEN }}" >> ${GITHUB_OUTPUT}
        else
          echo "token=${{ github.token }}" >> ${GITHUB_OUTPUT}
        fi
      shell: bash
    - name: Clone website repository on gh-pages branch
      uses: actions/checkout@v3
      with:
        token: ${{ steps.token_gh_pages.outputs.token }}
        ref: gh-pages
        fetch-depth: 0
        path: _build/html
    - name: Install dependencies
      run: |
        pip3 -q install sphinx-material
    - name: Generate sphinx website
      run: |
        rm -rf _build/html/* && make html
    - name: Fix permissions
      run: |
        sudo chown $USER _build -R
    - name: Clean up old Github pages branch
      if: github.repository == 'FEMlium/femlium.github.io' && github.event.inputs.reset_github_pages == 'yes'
      run: |
        if git ls-remote origin | grep -sw gh-pages 2>&1 >/dev/null; then git push origin --delete gh-pages; fi
    - name: Check that no tutorials have been deleted
      run: |
        pushd _build/html
        if [[ $(git ls-files --deleted tutorials | wc -l) -gt 0 ]]; then
          echo "The following tutorials have been deleted:"
          git ls-files --deleted tutorials
          exit 1
        fi
        popd
    - name: Deploy to GitHub pages
      if: github.repository == 'FEMlium/femlium.github.io' && github.ref == 'refs/heads/main'
      run: |
        SHA_SHORT=$(git rev-parse --short HEAD)
        pushd _build/html
        git config user.name "GitHub Actions"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git pull origin gh-pages
        [ -n "$(git status --porcelain=v1 2>/dev/null)" ] && git commit -m "deploy: ${SHA_SHORT}"
        git push origin gh-pages
        popd
      shell: bash
    - name: Deploy to GitHub artifacts
      if: github.repository == 'FEMlium/femlium.github.io' && github.ref != 'refs/heads/main'
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: _build/html
        retention-days: 1
    - name: Warn if scheduled workflow is about to be disabled
      if: github.repository == 'FEMlium/femlium.github.io' && github.ref == 'refs/heads/main' && github.event_name == 'schedule'
      uses: fem-on-colab/warn-workflow-about-to-be-disabled-action@main
      with:
        workflow-filename: website.yml
        days-elapsed: 50
